version: "3.8"

services:

  app-backend:
    build: ./docker/php/8.2
    container_name: tradeup-backend
    image: tradeup/backend:v1.0.0
    volumes:
      - ./:/var/www
    command: bash -c "composer install --working-dir=/var/www && php-fpm"
    networks:
      - tradeup-network

  app-nginx:
      image: nginx:latest
      container_name: tradeup-nginx
      restart: always
      tty: true
      ports:
          - "8081:8081"
      volumes:
          - ./:/var/www
          - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      networks:
          - tradeup-network
      depends_on:
          - app-backend

  app-frontend:
    build:
      context: .
      dockerfile: Dockerfile.vue.development
    container_name: tradeup-frontend
    image: tradeup/frontend:v1.0.0
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - 8080:8080
    networks:
        - tradeup-network
    depends_on:
      - app-backend

volumes:
  node_modules:
networks:
    tradeup-network:
        driver: bridge